eCommerceSite/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using eCommerceSite.Data;
using eCommerceSite.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace eCommerceSite.Controllers
{
    public class CartController : Controller
    {
        private readonly ProductContext _context;
        private readonly IHttpContextAccessor _httpContext;
        public CartController(ProductContext context, IHttpContextAccessor httpContext)
        {
            _context = context;
            _httpContext = httpContext;
        }
        public async Task<IActionResult> Add(int id)
        {
            Product p = await ProductDb.GetSingleProductAsync(_context, id);

            CookieHelper.AddProductToCart(_httpContext, p);

            return RedirectToAction("Index", "Product");
        }

        public IActionResult Summary()
        {
            return View(CookieHelper.GetCartProducts(_httpContext));
        }
    }
}

eCommerceSite/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using eCommerceSite.Data;
using eCommerceSite.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace eCommerceSite.Controllers
{
    public class UserController : Controller
    {
        private readonly ProductContext _context;
        public UserController(ProductContext context)
        {
            _context = context;
        }


        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel regi)
        {
            if (ModelState.IsValid)
            {
                bool isEmailTaken = await (from account in _context.Accounts
                                    where account.Email == regi.Email
                                    select account).AnyAsync();

                if (isEmailTaken)
                {
                    ModelState.AddModelError(nameof(RegisterViewModel.Email), "That email is already in use!");
                    return View(regi);
                };

                bool isUserTaken = await (from account in _context.Accounts
                                           where account.Username == regi.UserName
                                           select account).AnyAsync();

                if (isUserTaken)
                {
                    ModelState.AddModelError(nameof(RegisterViewModel.UserName), "That username is already in use!");
                    return View(regi);
                };

                UserAccount user = new UserAccount()
                {
                    DateOfBirth = regi.DateOfBirth ,
                    Email = regi.Email ,
                    Password = regi.Password ,
                    Username = regi.UserName
                };

                _context.Accounts.Add(user);
                await _context.SaveChangesAsync();

                LogUserIn(user.UserId);

                TempData["Message"] = $"Welcome {user.Username}, registration was a success!";
                return RedirectToAction("Index", "Home");
            }
            return View(regi);
        }

        [HttpGet]
        public IActionResult Login()
        {
            if (HttpContext.Session.GetInt32("UserId").HasValue)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel logger)
        {
            if (!ModelState.IsValid) { return View(logger); }

            //UserAccount account = await (from u in _context.Accounts
            //                             where (u.Username == logger.UsernameOrEmail ||
            //                             u.Email == logger.UsernameOrEmail) &&
            //                             u.Password == logger.Password
            //                             select u).SingleOrDefaultAsync();

            UserAccount account =
                await (_context.Accounts
                    .Where(ua => (ua.Username == logger.UsernameOrEmail ||
                                ua.Email == logger.UsernameOrEmail) &&
                                ua.Password == logger.Password)
                .SingleOrDefaultAsync());

            if (account == null)
            {
                ModelState.AddModelError(string.Empty, "Credentials were not found");

                return View(logger);
            }
            LogUserIn(account.UserId);

            return RedirectToAction("Index", "Home");
        }

        private void LogUserIn(int accountId)
        {
            HttpContext.Session.SetInt32("UserId", accountId);
        }

        public IActionResult Logout()
        {
            //remove all the session data
            HttpContext.Session.Clear();

            return RedirectToAction("Index","Home");
        }
    }
}

eCommerceSite/Views/Shared/_Layout.cshtml
@using Microsoft.EntityFrameworkCore
@inject IHttpContextAccessor sessionData
@inject eCommerceSite.Data.ProductContext database

@{ 
    int? userId = sessionData.HttpContext.Session.GetInt32("UserId");
    string userName = null;

    if(userId.HasValue)
    {
        if(sessionData.HttpContext.Session.GetString("Username") == null) {
            userName = await (from u in database.Accounts
                              where u.UserId == userId
                              select u.Username).SingleOrDefaultAsync();
            sessionData.HttpContext.Session.SetString("Username", userName);
        }
        else
        {
            userName = sessionData.HttpContext.Session.GetString("Username");
        }
    }
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eCommerceSite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="bg-dark text-light">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">eCommerceSite</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                        @if (userId == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-controller="User" asp-action="Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-controller="User" asp-action="Login">Login</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light disabled">Welcome @userName!</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-controller="User" asp-action="Logout">Logout</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Cart" asp-action="Summary">
                                @{ int total = @CookieHelper.GetAllCartProducts(sessionData); }

                                @if (total == 0)
                                {
                                    <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-cart" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd" d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm7 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z" />
                                    </svg>
                                }
                                else
                                {
                                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-cart-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd" d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm7 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z" />
                                    </svg>
                                    @total
                                }

                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top border-light footer text-muted">
        <div class="container ">
            &copy; 2020 - eCommerceSite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>